### ISSUE TITLE
停止tx-manager再启动后，tx-client报request fail. non tx-manager is alive

### ISSUE THREAD

**Issue by ipqihujf** [codingapi/txlcn-demo#28]
2020-03-15 11:10:07.637 DEBUG 21252 --- [o-12001-exec-10] c.c.t.tc.aspect.weave.DTXLogicWeaver     : <---- TxLcn start ---->
2020-03-15 11:10:07.637 DEBUG 21252 --- [o-12001-exec-10] c.c.t.t.c.context.DefaultGlobalContext   : Start TxContext[835009c74f537]
2020-03-15 11:10:07.637 DEBUG 21252 --- [o-12001-exec-10] c.c.t.t.c.t.TransactionControlTemplate   : create group > transaction type: lcn @group(835009c74f537)
2020-03-15 11:10:07.638 ERROR 21252 --- [o-12001-exec-10] c.c.txlcn.tc.core.DTXServiceExecutor     : 7a8822197032157eea2d988b70a4b567 @group(non)
2020-03-15 11:10:07.638 DEBUG 21252 --- [o-12001-exec-10] c.c.t.t.c.t.TransactionControlTemplate   : notify group > transaction type: lcn, state: 1. @group(835009c74f537)
2020-03-15 11:10:07.638  WARN 21252 --- [o-12001-exec-10] c.t.t.c.t.l.c.LcnTransactionCleanService : Non lcn connection when clear transaction.
2020-03-15 11:10:07.639 DEBUG 21252 --- [o-12001-exec-10] com.codingapi.txlcn.tc.txmsg.TMReporter  : report transaction transactionState error @group(835009c74f537)
2020-03-15 11:10:07.639 DEBUG 21252 --- [o-12001-exec-10] c.c.t.t.c.t.TransactionControlTemplate   : notify group exception state 1. @group(835009c74f537)
2020-03-15 11:10:07.639 DEBUG 21252 --- [o-12001-exec-10] c.c.t.t.c.context.DefaultGlobalContext   : Destroy TxContext[835009c74f537]
2020-03-15 11:10:07.639 DEBUG 21252 --- [o-12001-exec-10] c.c.txlcn.tc.core.DTXLocalContext        : clean thread local[DTXLocalContext]: DTXLocalContext(transactionType=lcn, groupId=835009c74f537, unitId=7a8822197032157eea2d988b70a4b567, resource=null, destroy=true, inGroup=false, attachment=null, sysTransactionState=1, userTransactionState=-1, proxy=false, justNow=false, proxyTmp=false)
2020-03-15 11:10:07.639 DEBUG 21252 --- [o-12001-exec-10] c.c.t.tc.aspect.weave.DTXLogicWeaver     : <---- TxLcn end ---->
2020-03-15 11:10:07.654 ERROR 21252 --- [o-12001-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.reflect.UndeclaredThrowableException] with root cause

com.codingapi.txlcn.txmsg.exception.RpcException: request fail. non tx-manager is alive.
	at com.codingapi.txlcn.tc.txmsg.LoopMessenger.request(LoopMessenger.java:168) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tc.txmsg.LoopMessenger.request0(LoopMessenger.java:142) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tc.txmsg.LoopMessenger.request(LoopMessenger.java:138) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tc.txmsg.LoopMessenger.createGroup(LoopMessenger.java:98) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tc.core.template.TransactionControlTemplate.createGroup(TransactionControlTemplate.java:89) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tc.core.transaction.lcn.control.LcnStartingTransaction.preBusinessCode(LcnStartingTransaction.java:49) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tc.core.DTXServiceExecutor.transactionRunning(DTXServiceExecutor.java:84) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tc.aspect.weave.DTXLogicWeaver.runTransaction(DTXLogicWeaver.java:96) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at com.codingapi.txlcn.tc.aspect.interceptor.TxLcnInterceptor.invoke(TxLcnInterceptor.java:46) ~[txlcn-tc-5.0.2.RELEASE.jar:5.0.2.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.13.RELEASE.jar:5.1.13.RELEASE]
	at com.sun.proxy.$Proxy127.execute(Unknown Source) ~[na:na]
	at org.txlcn.demo.servicea.DemoController.execute(DemoController.java:26) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]

**Comment by CHHP** [comment]
后面怎么解决的啊？

**Comment by hao-0904** [comment]
你解决了没，我也报错了
